app.default:
  client:
    id: acme
    secret: acmesecret
  user:
    username: admin
    password: topica@13579

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO

security.basic.enabled: false

server:
  address: 127.0.0.1
  port: 8000
  use-forward-headers: true
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: tomcat_access_log
      rename-on-rotate: false
      rotate: true
      max-http-post-size: 0
      server.tomcat.uri-encoding: UTF-8

spring:
  h2.console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:file:./target/data
    username: sa
    password:
    driver-class-name: org.h2.Driver
