app.default:
  client:
    id: acme
    secret: acmesecret
  user:
    username: admin
    password: topica@13579

spring:
  h2.console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:file:./target/data
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  address: 127.0.0.1
  port: 8000
  use-forward-headers: true

logging:
  level:
    org.springframework.security: INFO
