app.sso.service: http://localhost:8080

server:
  port: 9999
  servlet.session.timeout: 1800s

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: ${app.sso.service}/oauth/token
      user-authorization-uri: ${app.sso.service}/oauth/authorize
      user-logout-uri: ${app.sso.service}/oauth/exit
    resource:
      user-info-uri: ${app.sso.service}/me

spring.redis:
  host: 127.0.0.1
  password:
  port: 6379

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    